from more_move import *
from insertion_sort_binar import *
from try_plant import *
from pumkin import *
from wood import *
from carrot import *
from grass import *
from sunflower import *
from cactus import *